/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.SendMail;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.print.attribute.standard.JobMessageFromOperator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.MailData;

/**
 *
 * @author DatIT
 */
public final class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrom
     */
    public static String userEmail = "";
    public static String userPass = "";
    
    public MainForm() {
        LoginJD ljd = new LoginJD(this, true);
        ljd.setVisible(true);
        // 
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/email.png")));
        initComponents();
        this.setLocationRelativeTo(null);
        UserUpdate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBoxBody = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtBoxSubject = new javax.swing.JTextField();
        txtBoxToEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbTrangThai = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        txtBoxEmail = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto Email v0.1");

        txtBoxBody.setColumns(20);
        txtBoxBody.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBoxBody.setRows(5);
        txtBoxBody.setText("Nội dung");
        txtBoxBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBoxBodyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtBoxBody);

        jLabel1.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("GỬI EMAIL vjP pRo");

        txtBoxSubject.setFont(new java.awt.Font("Be Vietnam Medium", 0, 14)); // NOI18N
        txtBoxSubject.setText("Tiêu đề");
        txtBoxSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBoxSubjectMouseClicked(evt);
            }
        });
        txtBoxSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxSubjectActionPerformed(evt);
            }
        });

        txtBoxToEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBoxToEmail.setText("user@email.com");
        txtBoxToEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBoxToEmailMouseClicked(evt);
            }
        });
        txtBoxToEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxToEmailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Be Vietnam", 0, 14)); // NOI18N
        jLabel2.setText("Địa chỉ email nhận");

        lbTrangThai.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 12)); // NOI18N
        lbTrangThai.setText("Trạng thái:");

        lbStatus.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 12)); // NOI18N
        lbStatus.setText("Chờ");

        btnSend.setBackground(new java.awt.Color(0, 153, 0));
        btnSend.setText("GỬI");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtBoxEmail.setEditable(false);
        txtBoxEmail.setFont(new java.awt.Font("JetBrains Mono Medium", 2, 12)); // NOI18N

        jMenu1.setText("Tài khoản");

        jMenuItem1.setText("Đổi thông tin tài khoản");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chức năng");

        jMenuItem2.setText("Đang cập nhật");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtBoxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbTrangThai)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBoxToEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBoxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxToEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTrangThai)
                    .addComponent(lbStatus)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBoxToEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBoxToEmailMouseClicked
        // TODO add your handling code here:
        if (txtBoxToEmail.getText().equals("user@email.com")) {
            txtBoxToEmail.setText("");
        }
    }//GEN-LAST:event_txtBoxToEmailMouseClicked

    private void txtBoxToEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxToEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxToEmailActionPerformed

    private void txtBoxSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBoxSubjectMouseClicked
        // TODO add your handling code here:
        if (txtBoxSubject.getText().equals("Tiêu đề"))
            txtBoxSubject.setText("");
    }//GEN-LAST:event_txtBoxSubjectMouseClicked

    private void txtBoxBodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBoxBodyMouseClicked
        // TODO add your handling code here:
        if (txtBoxBody.getText().equals("Nội dung"))
            txtBoxBody.setText("");
    }//GEN-LAST:event_txtBoxBodyMouseClicked

    private void txtBoxSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxSubjectActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:

        //
        if (checkData()) {
            String body = txtBoxBody.getText();
            String subject = txtBoxSubject.getText();
            String toEmail = txtBoxToEmail.getText();
            MailData _mail = new MailData(toEmail, subject, body);
            if (SendMail.send(userEmail, userPass, _mail)) {
                JOptionPane.showMessageDialog(rootPane, "Gửi thành công !!!");
                lbStatus.setText("Thành công");
                lbStatus.setForeground(Color.GREEN);
            } else {
                lbStatus.setText("Thất bại");
                lbStatus.setForeground(Color.red);
                JOptionPane.showMessageDialog(rootPane,
                        "Gữi không thành công\n Kiểm tra lại thông tin tài khoản !");
            }
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        LoginJD lgjd = new LoginJD(this, true);
        lgjd.setVisible(true);
        UserUpdate();

    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private boolean checkData() {
        if (txtBoxBody.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nội dung không được để trống !");
            return false;
        }
        if (txtBoxToEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Địa chỉ không được để trống !");
            return false;
        }
        if (txtBoxBody.getText().equals("") || userEmail.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa đăng nhập !");
            return false;
        }
        return true;
    }
    
    public void UserUpdate() {
        txtBoxEmail.setText("Xin chào! " + userEmail);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JTextArea txtBoxBody;
    private javax.swing.JTextField txtBoxEmail;
    private javax.swing.JTextField txtBoxSubject;
    private javax.swing.JTextField txtBoxToEmail;
    // End of variables declaration//GEN-END:variables
}
